unicas.api.url=
unicas.api.username=
unicas.api.password=
unicas.api.key=
unicas.prop.applicationFormId=
# organizationId, if unset - instance (global) user is used
unicas.prop.organizationId=
unicas.prop.apiScope=
# date filter in format of yyyy-MM-dd, inclusive
unicas.prop.fromDate=
unicas.prop.toDate=
unicas.prop.skipFiles=