unicas.api.url=
unicas.api.username=
unicas.api.password=
unicas.api.key=
unicas.prop.applicationFormId=
unicas.prop.organizationId=
unicas.prop.programId=
# api scope: form, org, prog - can not exceed highest permissions of the user
# scope: form => must specify applicationFormId
# scope: org => must specify applicationFormId, organizationId
# scope: prog => must specify applicationFormId, organizationId, programId
unicas.prop.apiScope=
# date filter in format of yyyy-MM-dd, inclusive
unicas.prop.fromDate=
unicas.prop.toDate=
unicas.prop.skipFiles=
unicas.prop.useGzip=